language: go
git:
  quiet: true

before_install:
- go get -t -v ./...

script:
- go test -race -coverprofile=coverage.txt -covermode=atomic ./...
- go build

after_success:
- bash <(curl -s https://codecov.io/bash)
- ./tag-nightly.sh

before_deploy:
- go get github.com/inconshreveable/mousetrap
- go get github.com/konsorten/go-windows-terminal-sequences
- ./build.sh

deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file_glob: true
  file: bin/*
  prerelease: true
  overwrite: true
  skip_cleanup: true
  on:
    tags: true
