site_name: goops
theme: readthedocs
nav:
- Home: index.md
- Getting started: getting-started.md
- Features:
  - Auto semver: features/semver.md
  - Jira integration: features/jira.md
  - Docker stable & latest: features/docker.md
  - Github nightly tags: features/nightly-tags.md
- Examples: examples.md
- Commands:
  - setenv: commands/goops_setenv.md
  - transition: commands/goops_transition.md
- Plumbing commands:
  - version: commands/goops_version.md
markdown_extensions:
- admonition
site_dir: ../docs